#' Plot popbam trees
#'
#' This function plots and annotates trees generated by popbam
#' @param \code{tree} multiphlyo created by \code{read_popbam_tree()}
#' #' @param \code{root} name of taxon to root tree
#' @keywords POPBAM, trees, plot
#' @export
#' @examples
#' plot_popbam_trees()

plot_popbam_tree <- function(tree,root=FALSE){
  #add.scale.bar()
  for (i in 1:length(tree)){
    if (root!=FALSE)
    {tree[[i]] <- root(tree[[i]],root)}
    plot(ladderize(tree[[i]]))
    title(paste("chr ",tree[[i]]$chr,":",tree[[i]]$start,"-",tree[[i]]$end,"\n",tree[[i]]$nsites," aligned sites",sep="")) 
  }
}